version: '3.8'

services:
  db_dev:
    image: postgres:17
    env_file: .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"

  backend_dev:
    build:
      context: .
      dockerfile: docker/app_dev/Dockerfile
    env_file: .env
    depends_on:
      db_dev:
        condition: service_healthy

  gateway_dev:
    build:
      context: docker/nginx_dev
      dockerfile: Dockerfile
    env_file: .env
    depends_on: 
      - backend_dev
    ports:
      - "8000:80"

volumes:
  pg-data: